name = "ddcf-worker"
type = "javascript"

workers_dev = true
compatibility_date = "2022-02-26"

[env.production]
zone_id = "17027e56d602aef10f40f738170c2532"
account_id = "2d8991f7fef2afcf3748f55f827d9b87"
route = "https://ddcf.gravitaz.co.uk/"

[build]
command = "npm install-ci-test && npm run build"
[build.upload]
format = "service-worker"

