name: Deploy to Cloudflare Workers
on:
  push:
    branches:
      - main
  repository_dispatch:
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: 'Cloudflare Gravitaz Workers'
    timeout-minutes: 60
#    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Build and test
        run: npm ci
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: 'production'
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
